### ISSUE TITLE
Use of OpenMPI 1.8.5 in petsc

### ISSUE THREAD

**Issue by spco** [luca-heltai/dealii#86]
Hi Luca,

thanks for all your great work on these OSX packages. I recently updated to v8.4.pre.10 pre-release package, on Yosemite. Xcode and command line tools etc are up to date. This all installs fine, and all the examples run fine. I use it to run Aspect, and this also compiles happily. However, there seems to be an issue when using mpirun. Both Aspect and, say, step-32 run fine enough when called explicitly, but give an obscure error with `mpirun -np 4 ./step-32` etc:

`mpirun -np 4 ./step-32`
`[host-205-158.eduroam-local.wifi.le.ac.uk:05103] [[2105,0],0] mca_oob_tcp_recv_handler: invalid message type: 14`
`[host-205-158.eduroam-local.wifi.le.ac.uk:05103] [[2105,0],0] mca_oob_tcp_recv_handler: invalid message type: 14`
`[host-205-158.eduroam-local.wifi.le.ac.uk:05103] [[2105,0],0] mca_oob_tcp_recv_handler: invalid message type: 14`
`[host-205-158.eduroam-local.wifi.le.ac.uk:05103] [[2105,0],0] mca_oob_tcp_recv_handler: invalid message type: 14`
`--------------------------------------------------------------------------`
`mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.`
`--------------------------------------------------------------------------`

On investigation, this is using `/usr/local/bin/mpirun`. I'm not sure whether this error is because of an issue in my openmpi setup at this location, or because the deal.II package is configured using the openmpi from inside the petsc folder, and thus won't allow me to use my own openmpi. Could you advise? I think my openmpi setup is OK - it runs a test script with no error.

If I then swap to explicitly use the openmpi in the petsc folder, but there is a memory leak. Calling 

`/Applications/deal.II.app/Contents/Resources/opt/petsc-3264318/bin/mpirun -np 4 ./step-32`

and watching the memory usage in Activity Monitor shows this quickly consumes 10GB and beyond. I initially spotted this when the van keken benchmark in Aspect crashed after consuming 50GB. The same thing happens whether called from Terminal or within Xcode.

The link here https://github.com/open-mpi/ompi/issues/579 suggests this is because the petsc folder's openmpi is v1.8.5. Is there the possibility of a package without the buggy 1.8.5? I don't know whether that openmpi version is under your control, or whether it is too heavily packaged into petsc.

Bests,
Sam

**Comment by spco** [comment]
As a followup, I've downgraded to v8.4.0.pre.4, which is the last to use openmpi-1.6.5, and everything works fine (apart from a little loss of some of the latest deal.ii functionality, of course)

**Comment by luca-heltai** [comment]
Ciao, can you check that everything works fine with the final 8.4.0 release package, on the official dealii github?

**Comment by luca-heltai** [comment]
I never observed the memory leak you point out. I'll try to experiment a little, and if necessary, I'll try to upgrade a new version with open mpi 1.8.8.

**Comment by spco** [comment]
Hi Luca, I've just tested the new package and it still shows the same behaviour (tested with step-32 and ASPECT, from terminal and Xcode, both in Debug). I don't believe I have any odd settings in place (fresh Xcode project made using CXX and CC from the petsc folder, fresh deal.II.app).

El Capitan 10.11.3
$clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix

inside `build` subdirectory:
    $cmake -DCMAKE_C_COMPILER=/Applications/deal.II.app/Contents/Resources/opt/petsc-3264318/bin/mpicc -DCMAKE_CXX_COMPILER=/Applications/deal.II.app/Contents/Resources/opt/petsc-3264318/bin/mpicxx -G Xcode -DCMAKE_BUILD_TYPE=Debug ..
    -- ====================================================
    -- ============ Configuring ASPECT ====================
    -- ====================================================
    -- Found deal.II version 8.4.0 at '/Applications/deal.II.app/Contents/Resources/lib/cmake/deal.II'
-- Using PETSc = 'OFF'
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler using: Xcode
-- Check for working C compiler using: Xcode -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Xcode
-- Check for working CXX compiler using: Xcode -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Enabling dynamic loading of plugins from the input file
-- Looking for include file link.h
-- Looking for include file link.h - not found
-- Autopilot invoked
    ###
    #
    #  Project  aspect  set up with  deal.II-8.4.0  found at
    #      /Applications/deal.II.app/Contents/Resources
    #
    #  CMAKE_BUILD_TYPE:          Debug
    #
    #  You can now run
    #       $ make                - to compile and link the program
    #       $ make run            - to (compile, link and) run the program
    #
    #       $ make sign           - to sign the executable with the supplied OSX developer key
    #
    #       $ make debug          - to switch the build type to 'Debug'
    #       $ make release        - to switch the build type to 'Release'
    #
    #       $ make edit_cache     - to change (cached) configuration variables
    #                               and rerun the configure and generate phases of CMake
    #
    #       $ make strip_comments - to strip the source files in this
    #                               directory off the documentation comments
    #       $ make clean          - to remove the generated executable as well as
    #                               all intermediate compilation files
    #       $ make runclean       - to remove all output generated by the program
    #       $ make distclean      - to clean the directory from _all_ generated
    #                               files (includes clean, runclean and the removal
    #                               of the generated build system)
    #       $ make info           - to view this message again
    #
    #  Have a nice day!
    #
    ###
-- Performing Test HAVE_FP_EXCEPTIONS
-- Performing Test HAVE_FP_EXCEPTIONS - Failed
-- No support for feenableexcept(), disabling runtime floating point exception checks.
-- Writing config into detailed.log...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/sam/git/aspect-devel/build

**Comment by luca-heltai** [comment]
I'm rebuilding everything with mpi 1.10.2. Do you know if there are issues with this version (before I rebuild everything)?

**Comment by spco** [comment]
I'm not aware of any issues with 1.10.2, but I haven't used it. I'm guessing I can't use a standalone mpicc/cxx to test myself, as it wont match that used in compiling the .dmg?

**Comment by luca-heltai** [comment]
yes, that is correct. All libraries have to be compiled with the same compiler. I'm now rebuilding PETSc 3.6.3, SLEPc 3.6.2, SUNDIALS 2.6.2, Trilinos 10.6.2. If all of these go well, I'll upload a new package.

**Comment by spco** [comment]
Much appreciated!

**Comment by luca-heltai** [comment]
Can you try with the new package I just uploaded? This one uses everything recompiled from scratch with openmpi 1.10.2...

**Comment by spco** [comment]
Thanks Luca! I've tested this with ASPECT and it works perfectly - no memory leak in sight!

**Comment by spco** [comment]
I'm happy to close this issue if you'd like. Thanks once again!

**Comment by luca-heltai** [comment]
My pleasure!

:)
